bucket_prefix : joannah

s3main : 
  access_key : 
  access_secret : 
  region : us-east-1 
  endpoint : 
  port :  
  display_name : 
  email :  
  is_secure : 
  SSE : AES256

  s3dir : folder
  dir : ../data

# s3alt :
#     access_key : NOPQRSTUVWXYZABCDEFG
#     access_secret : nopqrstuvwxyzabcdefghijklmnabcdefghijklm
#     bucket : bucket1
#     region : mexico
#     display_name :
#     email : 
#     SSE : AES256
#     kmskeyid : barbican_key_id
#     is_secure : false

#     s3dir : folder
#     dir : '../data'
